// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	goose "github.com/pressly/goose/v3"
)

type Provider struct {
	DownStub        func(context.Context) (*goose.MigrationResult, error)
	downMutex       sync.RWMutex
	downArgsForCall []struct {
		arg1 context.Context
	}
	downReturns struct {
		result1 *goose.MigrationResult
		result2 error
	}
	downReturnsOnCall map[int]struct {
		result1 *goose.MigrationResult
		result2 error
	}
	StatusStub        func(context.Context) ([]*goose.MigrationStatus, error)
	statusMutex       sync.RWMutex
	statusArgsForCall []struct {
		arg1 context.Context
	}
	statusReturns struct {
		result1 []*goose.MigrationStatus
		result2 error
	}
	statusReturnsOnCall map[int]struct {
		result1 []*goose.MigrationStatus
		result2 error
	}
	UpStub        func(context.Context) ([]*goose.MigrationResult, error)
	upMutex       sync.RWMutex
	upArgsForCall []struct {
		arg1 context.Context
	}
	upReturns struct {
		result1 []*goose.MigrationResult
		result2 error
	}
	upReturnsOnCall map[int]struct {
		result1 []*goose.MigrationResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Provider) Down(arg1 context.Context) (*goose.MigrationResult, error) {
	fake.downMutex.Lock()
	ret, specificReturn := fake.downReturnsOnCall[len(fake.downArgsForCall)]
	fake.downArgsForCall = append(fake.downArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DownStub
	fakeReturns := fake.downReturns
	fake.recordInvocation("Down", []interface{}{arg1})
	fake.downMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Provider) DownCallCount() int {
	fake.downMutex.RLock()
	defer fake.downMutex.RUnlock()
	return len(fake.downArgsForCall)
}

func (fake *Provider) DownCalls(stub func(context.Context) (*goose.MigrationResult, error)) {
	fake.downMutex.Lock()
	defer fake.downMutex.Unlock()
	fake.DownStub = stub
}

func (fake *Provider) DownArgsForCall(i int) context.Context {
	fake.downMutex.RLock()
	defer fake.downMutex.RUnlock()
	argsForCall := fake.downArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Provider) DownReturns(result1 *goose.MigrationResult, result2 error) {
	fake.downMutex.Lock()
	defer fake.downMutex.Unlock()
	fake.DownStub = nil
	fake.downReturns = struct {
		result1 *goose.MigrationResult
		result2 error
	}{result1, result2}
}

func (fake *Provider) DownReturnsOnCall(i int, result1 *goose.MigrationResult, result2 error) {
	fake.downMutex.Lock()
	defer fake.downMutex.Unlock()
	fake.DownStub = nil
	if fake.downReturnsOnCall == nil {
		fake.downReturnsOnCall = make(map[int]struct {
			result1 *goose.MigrationResult
			result2 error
		})
	}
	fake.downReturnsOnCall[i] = struct {
		result1 *goose.MigrationResult
		result2 error
	}{result1, result2}
}

func (fake *Provider) Status(arg1 context.Context) ([]*goose.MigrationStatus, error) {
	fake.statusMutex.Lock()
	ret, specificReturn := fake.statusReturnsOnCall[len(fake.statusArgsForCall)]
	fake.statusArgsForCall = append(fake.statusArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.StatusStub
	fakeReturns := fake.statusReturns
	fake.recordInvocation("Status", []interface{}{arg1})
	fake.statusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Provider) StatusCallCount() int {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	return len(fake.statusArgsForCall)
}

func (fake *Provider) StatusCalls(stub func(context.Context) ([]*goose.MigrationStatus, error)) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = stub
}

func (fake *Provider) StatusArgsForCall(i int) context.Context {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	argsForCall := fake.statusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Provider) StatusReturns(result1 []*goose.MigrationStatus, result2 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	fake.statusReturns = struct {
		result1 []*goose.MigrationStatus
		result2 error
	}{result1, result2}
}

func (fake *Provider) StatusReturnsOnCall(i int, result1 []*goose.MigrationStatus, result2 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	if fake.statusReturnsOnCall == nil {
		fake.statusReturnsOnCall = make(map[int]struct {
			result1 []*goose.MigrationStatus
			result2 error
		})
	}
	fake.statusReturnsOnCall[i] = struct {
		result1 []*goose.MigrationStatus
		result2 error
	}{result1, result2}
}

func (fake *Provider) Up(arg1 context.Context) ([]*goose.MigrationResult, error) {
	fake.upMutex.Lock()
	ret, specificReturn := fake.upReturnsOnCall[len(fake.upArgsForCall)]
	fake.upArgsForCall = append(fake.upArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.UpStub
	fakeReturns := fake.upReturns
	fake.recordInvocation("Up", []interface{}{arg1})
	fake.upMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Provider) UpCallCount() int {
	fake.upMutex.RLock()
	defer fake.upMutex.RUnlock()
	return len(fake.upArgsForCall)
}

func (fake *Provider) UpCalls(stub func(context.Context) ([]*goose.MigrationResult, error)) {
	fake.upMutex.Lock()
	defer fake.upMutex.Unlock()
	fake.UpStub = stub
}

func (fake *Provider) UpArgsForCall(i int) context.Context {
	fake.upMutex.RLock()
	defer fake.upMutex.RUnlock()
	argsForCall := fake.upArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Provider) UpReturns(result1 []*goose.MigrationResult, result2 error) {
	fake.upMutex.Lock()
	defer fake.upMutex.Unlock()
	fake.UpStub = nil
	fake.upReturns = struct {
		result1 []*goose.MigrationResult
		result2 error
	}{result1, result2}
}

func (fake *Provider) UpReturnsOnCall(i int, result1 []*goose.MigrationResult, result2 error) {
	fake.upMutex.Lock()
	defer fake.upMutex.Unlock()
	fake.UpStub = nil
	if fake.upReturnsOnCall == nil {
		fake.upReturnsOnCall = make(map[int]struct {
			result1 []*goose.MigrationResult
			result2 error
		})
	}
	fake.upReturnsOnCall[i] = struct {
		result1 []*goose.MigrationResult
		result2 error
	}{result1, result2}
}

func (fake *Provider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Provider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
