// Code generated by muxt generate --use-receiver-type=Provider --use-receiver-type-package=github.com/pressly/goose/v3 --output-receiver-interface=Provider --output-routes-func routes --output-template-data-type templateData. DO NOT EDIT.
// muxt version: v0.18.0-dev.6
package gooseglass

import (
	"cmp"
	"errors"
	"fmt"
	"net/http"
	"path"
	"strconv"
)

type Provider interface {
	providerRoutesReceiver
}

func routes(mux *http.ServeMux, receiver Provider) TemplateRoutePaths {
	pathsPrefix := ""
	providerroutes(mux, receiver, pathsPrefix)
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type templateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *templateData[R, T]) MuxtVersion() string {
	const muxtVersion = "v0.18.0-dev.6"
	return muxtVersion
}

func (data *templateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *templateData[R, T]) Result() T {
	return data.result
}

func (data *templateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *templateData[R, T]) StatusCode(statusCode int) *templateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *templateData[R, T]) Header(key, value string) *templateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *templateData[R, T]) Ok() bool {
	return data.okay
}

func (data *templateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *templateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *templateData[R, T]) Redirect(url string, code int) (*templateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Status() string {
	return "/"
}

func (routePaths TemplateRoutePaths) Down() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "down")
}

func (routePaths TemplateRoutePaths) DownTo(version int64) string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "down-to", strconv.FormatInt(int64(version), 10))
}

func (routePaths TemplateRoutePaths) Up() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "up")
}

func (routePaths TemplateRoutePaths) UpTo(version int64) string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "up-to", strconv.FormatInt(int64(version), 10))
}
