// Code generated by muxt generate --use-receiver-type=Provider --use-receiver-type-package=github.com/pressly/goose/v3 --output-receiver-interface=Provider --output-routes-func=routes --output-template-data-type=templateData. DO NOT EDIT.
// muxt version: v0.18.3

package gooseglass

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"

	goose "github.com/pressly/goose/v3"
)

type Provider interface {
	Status(ctx context.Context) ([]*goose.MigrationStatus, error)
	Down(ctx context.Context) (*goose.MigrationResult, error)
	DownTo(ctx context.Context, version int64) ([]*goose.MigrationResult, error)
	Up(ctx context.Context) ([]*goose.MigrationResult, error)
	UpTo(ctx context.Context, version int64) ([]*goose.MigrationResult, error)
}

func routes(mux *http.ServeMux, receiver Provider) TemplateRoutePaths {
	pathsPrefix := ""
	mux.HandleFunc("GET /", func(response http.ResponseWriter, request *http.Request) {
		var td = templateData[Provider, []*goose.MigrationStatus]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.Status(ctx)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
			td.result = td.result
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "GET / Status(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /down", func(response http.ResponseWriter, request *http.Request) {
		var td = templateData[Provider, *goose.MigrationResult]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.Down(ctx)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
			td.result = td.result
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /down Down(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /down-to/{version}", func(response http.ResponseWriter, request *http.Request) {
		var td = templateData[Provider, []*goose.MigrationResult]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		versionParsed, err := strconv.ParseInt(request.PathValue("version"), 10, 64)
		if err != nil {
			td.errList = append(td.errList, err)
			td.errStatusCode = http.StatusBadRequest
		}
		version := versionParsed
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.DownTo(ctx, version)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
			td.result = td.result
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /down-to/{version} DownTo(ctx, version)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /up", func(response http.ResponseWriter, request *http.Request) {
		var td = templateData[Provider, []*goose.MigrationResult]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.Up(ctx)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
			td.result = td.result
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /up Up(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /up-to/{version}", func(response http.ResponseWriter, request *http.Request) {
		var td = templateData[Provider, []*goose.MigrationResult]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		versionParsed, err := strconv.ParseInt(request.PathValue("version"), 10, 64)
		if err != nil {
			td.errList = append(td.errList, err)
			td.errStatusCode = http.StatusBadRequest
		}
		version := versionParsed
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.UpTo(ctx, version)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
			td.result = td.result
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /up-to/{version} UpTo(ctx, version)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type templateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *templateData[R, T]) MuxtVersion() string {
	const muxtVersion = "v0.18.3"
	return muxtVersion
}

func (data *templateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *templateData[R, T]) Result() T {
	return data.result
}

func (data *templateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *templateData[R, T]) StatusCode(statusCode int) *templateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *templateData[R, T]) Header(key, value string) *templateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *templateData[R, T]) Ok() bool {
	return data.okay
}

func (data *templateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *templateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *templateData[R, T]) Redirect(url string, code int) (*templateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Status() string {
	return "/"
}

func (routePaths TemplateRoutePaths) Down() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "down")
}

func (routePaths TemplateRoutePaths) DownTo(version int64) string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "down-to", strconv.FormatInt(int64(version), 10))
}

func (routePaths TemplateRoutePaths) Up() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "up")
}

func (routePaths TemplateRoutePaths) UpTo(version int64) string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "up-to", strconv.FormatInt(int64(version), 10))
}
